### PR TITLE
Ben speed versus accuracy pareto

### PR DESCRIPTION
**Pull request by elmisback**
@benwang33--provide a description of the changes on this branch and merge when ready (probably after a rebase and resolving conflicts)!

### CODE REVIEW

**Comment by elmisback** [comment]
Merged main into this to bring it up to date

**Comment by elmisback** [comment]
@benwang33 This is working now--please add the description of changes on this branch vs main as requested and merge into main before doing any further work!

**Comment by elmisback** [comment]
The issue was that you have to specify a range for radius values on the plot object itself, pretty tricky 
image

**Comment by benwang33** [comment]
This pull request introduces a speed vs. accuracy Pareto curve to Odyssey.

A new tab for the Pareto curve is added on the left-hand side of Odyssey, beneath the error plot and derivation sections. This feature supports multiple points and allows for dynamic updates when their respective expressions are selected.

For instance, in the provided example, clicking on the first point enlarges its display on the graph.

image

**Pull request merged**
