### PR TITLE
Add async API calls.

### PR DESCRIPTION
**Pull request by zaneenders**
This PR switches Odyessy to using the new Async for the API's that are available to be called that way. I don't know if that is what we want to do but it did make testing that the API's were working correctly with this new calling convention when testing locally.

This PR does rely on this [Herbie PR ](https://github.com/herbie-fp/herbie/pull/991)to enable CORS for the `checkstatus` endpoint. This has been merged with main now.

### CODE REVIEW

**Comment by zaneenders** [comment]
Let me know how I can help.

**Comment by zaneenders** [comment]
Just thought of a bug/error in this code. 
If for some reason the request times out (10s / counter reaches 100) an error is not thrown in this state and the function proceeds as if the job is ready to be collected. Will update to throw an error in this state.

**Comment by elmisback** [comment]
Confirmed the server is running a sufficiently recent version of Odyssey to support this. Remaining steps:

- [ ] Update Herbie binaries with sufficiently-recent version of Odyssey
- [ ] Test locally
- [ ] Merge

**Comment by elmisback** [comment]
I'll test against the updated server today, won't point to the server or merge yet

**Comment by elmisback** [comment]
No progress due to OOPSLA

**Comment by elmisback** [comment]
No progress this week due to generals, but I should have some time to work on this on Thursday/Friday. I'll test against the server now that it's updated and switch local Odyssey to point to the server until binaries are updated.

**Comment by zaneenders** [comment]
Worked on adding a fallback check if the async API's don't exist. Getting some weird errors with errors not being caught. 
Will circle back on.

**Comment by elmisback** [comment]
I'm merging this branch now, tested locally and it works.

**Pull request merged**
